### ISSUE TITLE
Density from T and S

### ISSUE THREAD

**Issue by fhmjones** [jamiebyer/ocgy-dataviewer#2]
- [x] add density to the input files (CSV) by using gsw to calculate from S and T
- [x] test density calculations with example we have (5-6 points?) set up as a "dummy" station. 
- [x] ask instructors for a data set with density and S, T to test (once more) the gsw code. 
- [x] how  important is "correct" S, T? i.e. S & T measured directly from CTD instrument OK? Stephanie says probably.
- [x] Let's add an explanation of steps taken to generate all data. Easy for most (measured or obtained form eGreotraces) but more complicated for density, including two steps of calculation - and resources used. This is normal "attribution" when delivering a design, development or research result. i.e. "full disclosure" so others can reproduce results without asking for more details.

**Comment by jamiebyer** [comment]
I think the last point in the list, about using the "correct" S, T is referring to using practical vs. absolute salinity for the density calculation. Practical salinity is given in the original data. Absolute salinity can be calculated with the gsw library, using practical salinity, pressure, longitude, and latitude. The calculation was pretty easy to do so right now I am using absolute salinity for the calculation. I tested it out on the fake station and the results differed by about 0.2. Though it could probably vary more or less with different pressure, lon, lat.

**Comment by fhmjones** [comment]
Great - thanks for clarifying. I'm learning lots with this activity. 
The fifth checkbox is a result of your effort here.
